### ISSUE TITLE
Verificar si el usuario esta loggeado

### ISSUE THREAD

**Issue by oalberto96** [oalberto96/Emprendedores#1]
Verificar en cada vista si el usuario esta loggeado para restringir a usuarios aonimos el uso del servicio

**Comment by oalberto96** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Iniciar Sesion](https://trello.com/c/wvmmbGQu/28-iniciar-sesion)

**Comment by bryallini96** [comment]
este ya quedo no?

**Comment by oalberto96** [comment]
Sí
