### ISSUE TITLE
Mostrar error al usuario al registrar

### ISSUE THREAD

**Issue by oalberto96** [oalberto96/Emprendedores#3]

**Comment by oalberto96** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Registrar Usuario](https://trello.com/c/hA3CArcE/27-registrar-usuario)

**Comment by bryallini96** [comment]
Que error se debe de mostrar?

**Comment by oalberto96** [comment]
Lo mismo me pregunto, mí yo del pasado olvidó la descripción

**Comment by bryallini96** [comment]
jajajajaja, Cerrado el Issue entonces
